/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SortingRouteImport } from './routes/sorting'
import { Route as SearchingRouteImport } from './routes/searching'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as LinkedListRouteImport } from './routes/linked-list'
import { Route as HeapRouteImport } from './routes/heap'
import { Route as HashTableRouteImport } from './routes/hash-table'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DequeRouteImport } from './routes/deque'
import { Route as ComplexityRouteImport } from './routes/complexity'
import { Route as CircularQueueRouteImport } from './routes/circular-queue'
import { Route as BstRouteImport } from './routes/bst'
import { Route as ArrayRouteImport } from './routes/array'
import { Route as IndexRouteImport } from './routes/index'

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchingRoute = SearchingRouteImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedListRoute = LinkedListRouteImport.update({
  id: '/linked-list',
  path: '/linked-list',
  getParentRoute: () => rootRouteImport,
} as any)
const HeapRoute = HeapRouteImport.update({
  id: '/heap',
  path: '/heap',
  getParentRoute: () => rootRouteImport,
} as any)
const HashTableRoute = HashTableRouteImport.update({
  id: '/hash-table',
  path: '/hash-table',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DequeRoute = DequeRouteImport.update({
  id: '/deque',
  path: '/deque',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplexityRoute = ComplexityRouteImport.update({
  id: '/complexity',
  path: '/complexity',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularQueueRoute = CircularQueueRouteImport.update({
  id: '/circular-queue',
  path: '/circular-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const BstRoute = BstRouteImport.update({
  id: '/bst',
  path: '/bst',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrayRoute = ArrayRouteImport.update({
  id: '/array',
  path: '/array',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/bst': typeof BstRoute
  '/circular-queue': typeof CircularQueueRoute
  '/complexity': typeof ComplexityRoute
  '/deque': typeof DequeRoute
  '/graph': typeof GraphRoute
  '/hash-table': typeof HashTableRoute
  '/heap': typeof HeapRoute
  '/linked-list': typeof LinkedListRoute
  '/queue': typeof QueueRoute
  '/quiz': typeof QuizRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/bst': typeof BstRoute
  '/circular-queue': typeof CircularQueueRoute
  '/complexity': typeof ComplexityRoute
  '/deque': typeof DequeRoute
  '/graph': typeof GraphRoute
  '/hash-table': typeof HashTableRoute
  '/heap': typeof HeapRoute
  '/linked-list': typeof LinkedListRoute
  '/queue': typeof QueueRoute
  '/quiz': typeof QuizRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/bst': typeof BstRoute
  '/circular-queue': typeof CircularQueueRoute
  '/complexity': typeof ComplexityRoute
  '/deque': typeof DequeRoute
  '/graph': typeof GraphRoute
  '/hash-table': typeof HashTableRoute
  '/heap': typeof HeapRoute
  '/linked-list': typeof LinkedListRoute
  '/queue': typeof QueueRoute
  '/quiz': typeof QuizRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/stack': typeof StackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/array'
    | '/bst'
    | '/circular-queue'
    | '/complexity'
    | '/deque'
    | '/graph'
    | '/hash-table'
    | '/heap'
    | '/linked-list'
    | '/queue'
    | '/quiz'
    | '/searching'
    | '/sorting'
    | '/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/array'
    | '/bst'
    | '/circular-queue'
    | '/complexity'
    | '/deque'
    | '/graph'
    | '/hash-table'
    | '/heap'
    | '/linked-list'
    | '/queue'
    | '/quiz'
    | '/searching'
    | '/sorting'
    | '/stack'
  id:
    | '__root__'
    | '/'
    | '/array'
    | '/bst'
    | '/circular-queue'
    | '/complexity'
    | '/deque'
    | '/graph'
    | '/hash-table'
    | '/heap'
    | '/linked-list'
    | '/queue'
    | '/quiz'
    | '/searching'
    | '/sorting'
    | '/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrayRoute: typeof ArrayRoute
  BstRoute: typeof BstRoute
  CircularQueueRoute: typeof CircularQueueRoute
  ComplexityRoute: typeof ComplexityRoute
  DequeRoute: typeof DequeRoute
  GraphRoute: typeof GraphRoute
  HashTableRoute: typeof HashTableRoute
  HeapRoute: typeof HeapRoute
  LinkedListRoute: typeof LinkedListRoute
  QueueRoute: typeof QueueRoute
  QuizRoute: typeof QuizRoute
  SearchingRoute: typeof SearchingRoute
  SortingRoute: typeof SortingRoute
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked-list': {
      id: '/linked-list'
      path: '/linked-list'
      fullPath: '/linked-list'
      preLoaderRoute: typeof LinkedListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heap': {
      id: '/heap'
      path: '/heap'
      fullPath: '/heap'
      preLoaderRoute: typeof HeapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash-table': {
      id: '/hash-table'
      path: '/hash-table'
      fullPath: '/hash-table'
      preLoaderRoute: typeof HashTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deque': {
      id: '/deque'
      path: '/deque'
      fullPath: '/deque'
      preLoaderRoute: typeof DequeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complexity': {
      id: '/complexity'
      path: '/complexity'
      fullPath: '/complexity'
      preLoaderRoute: typeof ComplexityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circular-queue': {
      id: '/circular-queue'
      path: '/circular-queue'
      fullPath: '/circular-queue'
      preLoaderRoute: typeof CircularQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bst': {
      id: '/bst'
      path: '/bst'
      fullPath: '/bst'
      preLoaderRoute: typeof BstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/array': {
      id: '/array'
      path: '/array'
      fullPath: '/array'
      preLoaderRoute: typeof ArrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrayRoute: ArrayRoute,
  BstRoute: BstRoute,
  CircularQueueRoute: CircularQueueRoute,
  ComplexityRoute: ComplexityRoute,
  DequeRoute: DequeRoute,
  GraphRoute: GraphRoute,
  HashTableRoute: HashTableRoute,
  HeapRoute: HeapRoute,
  LinkedListRoute: LinkedListRoute,
  QueueRoute: QueueRoute,
  QuizRoute: QuizRoute,
  SearchingRoute: SearchingRoute,
  SortingRoute: SortingRoute,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
